# -*- coding: utf-8 -*-
"""app_ver.2

Automatically generated by Colab

Original file is located at
    https://colab.research.google.com/drive/121fXPIYPnaG28exA5pFoZh3ZgMM79fz2
"""

# app.py
import streamlit as st
from app_M2T1P8 import solver_parttime
import random, numpy as np

# --- ตั้ง seed ---
random.seed(42)
np.random.seed(42)

st.set_page_config(page_title="Part-time Scheduler", layout="wide")

st.title("🗓️ Part-time Employee Scheduler")
st.markdown("จัดตารางพนักงานพาร์ทไทม์สำหรับร้านอาหาร")



# --- กรอกชื่อพนักงาน ---
#employee_names_input = st.text_input("กรอกชื่อพนักงาน (คั่นด้วย ,)")
#employee_names = [name.strip() for name in employee_names_input.split(",") if name.strip()]
#num_employees = len(employee_names)



# --- หัวข้อใหญ่พร้อมวงกลมเลข 1 ---
st.markdown("""
<div style="display:flex; align-items:center; margin-bottom:4px;">
    <div style="
        width: 36px; 
        height: 36px; 
        background-color: #1A2A4F; 
        border-radius: 50%; 
        display: flex; 
        align-items: center; 
        justify-content: center; 
        color: white; 
        font-weight: bold;
        font-size: 18px;
        margin-right: 10px;">
        1
    </div>
    <h2 style="margin: 0;">รายชื่อพนักงาน</h2>
</div>

<p style="color:#555; margin-top:0; margin-bottom:2px;">
กรอกรายชื่อพนักงาน (คั่นชื่อด้วย ,)
</p>
""", unsafe_allow_html=True)

# --- ช่องกรอกชื่อพนักงาน ---
employee_names_input = st.text_input(" ", placeholder="ตัวอย่าง: แนน, บอล, มิว, เจ")
employee_names = [name.strip() for name in employee_names_input.split(",") if name.strip()]
num_employees = len(employee_names)

# --- แสดงผลหลังกรอก ---
if employee_names:
    st.success(f"✅ มีพนักงานทั้งหมด {num_employees} คน")
    st.write("รายชื่อ:", employee_names)

   


# --- ประมวลผลรายชื่อ ---
employee_names = [name.strip() for name in employee_names_input.split(",") if name.strip()]
num_employees = len(employee_names)

# --- แสดงผลลัพธ์เมื่อกรอกแล้ว ---
if employee_names:
    st.success(f"✅ มีพนักงานทั้งหมด {num_employees} คน")
    st.write("รายชื่อ:", employee_names)


# --- เลือกเดือน ---
month = st.selectbox("เลือกเดือน", ["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน",
                                     "กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"])

# --- กรอกเงื่อนไขพนักงาน ---
st.subheader("เงื่อนไขพนักงาน (วันและกะที่สะดวก)")
all_employees_avail = {}
day_map = {"อาทิตย์":1,"จันทร์":2,"อังคาร":3,"พุธ":4,"พฤหัส":5,"ศุกร์":6}
shift_map = {"1":1,"2":2,"3":3,"4":4}

for idx, name in enumerate(employee_names, start=1):
    with st.expander(f"{name}"):
        days = st.multiselect("วันสะดวก", list(day_map.keys()), key=f"days_{idx}")
        shifts = st.multiselect("กะสะดวก", list(shift_map.keys()), key=f"shifts_{idx}")
        
        # สร้าง dict สำหรับวันทั้งหมดก่อน
        emp_avail = {}
        for d_name, d_num in day_map.items():
            # ถ้าวันนั้นเลือกวัน ก็เอากะที่เลือก ถ้าไม่เลือกเลย ให้เป็น []
            if d_name in days:
                emp_avail[d_num] = [shift_map[s] for s in shifts] if shifts else []
            else:
                emp_avail[d_num] = []
        all_employees_avail[idx] = emp_avail

# --- จำนวนพนักงานหลักต่อกะ ---
st.subheader("จำนวนพนักงานหลักต่อกะ")
W_per_t = {t: st.number_input(f"กะ {t}", min_value=0, value=1, step=1, key=f"main_{t}") for t in range(1,5)}

# --- จำนวนพนักงานสำรองต่อกะ ---
st.subheader("จำนวนพนักงานสำรองต่อกะ")
W_backup = {t: st.number_input(f"กะ {t}", min_value=0, value=1, step=1, key=f"backup_{t}") for t in range(1,5)}

# --- จำกัดจำนวนกะสูงสุด ---
st.subheader("จำนวนกะสูงสุด/สัปดาห์ ต่อคน")
max_shift = st.number_input("", min_value=1, value=3)

# --- จำกัดจำนวนกะต่ำสุด ---
st.subheader("จำนวนกะต่ำสุด/สัปดาห์ ต่อคน")
min_shift = st.number_input("", min_value=0, value=1) 

# --- ปุ่ม Solve ---
if st.button("สร้างตารางงาน"):
    data = {
        "num_employees": num_employees,
        "W_per_t": W_per_t,
        "max_shift_i": max_shift,
        "min_shift_i": min_shift,  # เพิ่มตรงนี้
        "P_idt": all_employees_avail,
        "cost_per_shift": {1:320,2:160,3:160,4:160},
        "absent": {}  # ป้องกัน KeyError
    }
    result = solver_parttime(data)

    st.success(f"ค่าใช้จ่ายรวม: {result['total_cost']} บาท/สัปดาห์")

    st.subheader("ตารางพนักงานหลัก (Main)")
    for d in range(1,7):
        st.write(f"Day {d}")
        for t in range(1,5):
            st.write(f"Shift {t}: {result['main'][(d,t)]}")

    st.subheader("ตารางพนักงานสำรอง (Backup)")
    for d in range(1,7):
        st.write(f"Day {d}")
        for t in range(1,5):
            st.write(f"Shift {t}: {result['backup'][(d,t)]}")
