# -*- coding: utf-8 -*-
"""app_M2T1P8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1owtezohLnn33qKd5WD0ZFL8dcB8PkcfN
"""

pip install pulp

all_employees_avail = {
    1: {  1: [1,2,3,4],
          2: [],
          3: [1,2,3,4],
          4: [],
          5: [],
          6: []
       },
    2: {  1: [1,2,3,4],
          2: [1,2,3,4],
          3: [],
          4: [],
          5: [1,2,3,4],
          6: [1,2,3,4]
       },
    3: {  1: [2,3,4],
          2: [2,3,4],
          3: [],
          4: [2,3,4],
          5: [],
          6: [2,3,4]
       },
    4: {  1: [1,2,3,4],
          2: [1,2,3,4],
          3: [],
          4: [],
          5: [],
          6: [1,2,3,4]
       },
    5: {  1: [1,2,3,4],
          2: [1,2,3,4],
          3: [],
          4: [],
          5: [],
          6: [1,2,3,4]
       },
    6: {  1: [2,3,4],
          2: [],
          3: [2,3,4],
          4: [],
          5: [2,3,4],
          6: []
       },
    7: {  1: [2,3,4],
          2: [],
          3: [2,3,4],
          4: [2,3,4],
          5: [2,3,4],
          6: [2,3,4]
       },
    8: {  1: [2,3,4],
          2: [2,3,4],
          3: [2,3,4],
          4: [2,3,4],
          5: [],
          6: []
       },
    9: {  1: [3,4],
          2: [],
          3: [3,4],
          4: [3,4],
          5: [3,4],
          6: [3,4]
       },
    10: { 1: [1,2,3,4],
          2: [1,2,3,4],
          3: [],
          4: [],
          5: [1,2,3,4],
          6: []
       },
    11: { 1: [1,2,3,4],
          2: [],
          3: [],
          4: [1,2,3,4],
          5: [1,2,3,4],
          6: [1,2,3,4]
       },
    12: { 1: [1,2,3,4],
          2: [1,2,3,4],
          3: [],
          4: [],
          5: [],
          6: [1,2,3,4]
       },
    13: { 1: [2,3,4],
          2: [],
          3: [2,3,4],
          4: [],
          5: [2,3,4],
          6: [2,3,4]
       },
    14: { 1: [1,2,3,4],
          2: [1,2,3,4],
          3: [1,2,3,4],
          4: [],
          5: [1,2,3,4],
          6: []
       },
    15: { 1: [1,2,3,4],
          2: [],
          3: [],
          4: [1,2,3,4],
          5: [],
          6: []
       },
    16: { 1: [2,3,4],
          2: [2,3,4],
          3: [],
          4: [],
          5: [2,3,4],
          6: [2,3,4]
       },
}

data = {
    "num_employees": 16,
    "W_per_t": {1:1, 2:2, 3:3, 4:2},
    "max_shift_i": 3,
    "P_idt": all_employees_avail,
    "cost_per_shift": {1:320, 2:160, 3:160, 4:160},
    "absent": {}  # ป้องกัน KeyError
}

# Default employee names
employee_names = ["Emp"+str(i) for i in range(1,17)]
num_employees = len(employee_names)

import pulp
import random, numpy as np
import streamlit as st
from solver import solver_parttime

st.set_page_config(page_title="Part-time Scheduler", layout="wide")
st.title("Part-time Employee Scheduler")

# ให้กรอกชื่อพนักงานเองก็ได้ หรือใช้ค่า default
employee_names_input = st.text_input("กรอกชื่อพนักงาน (คั่นด้วย ,)", value=",".join(employee_names))
employee_names = [name.strip() for name in employee_names_input.split(",") if name.strip()]

# ปุ่มสร้างตารางงาน
if st.button("สร้างตารางงาน"):
    result = solver_parttime(data)
    st.subheader("ตารางพนักงานหลัก (Main)")
    for d in range(1,7):
        st.write(f"Day {d}")
        for t in range(1,5):
            st.write(f"Shift {t}: {result['main'][(d,t)]}")

    st.subheader("ตารางพนักงานสำรอง (Backup)")
    for d in range(1,7):
        st.write(f"Day {d}")
        for t in range(1,5):
            st.write(f"Shift {t}: {result['backup'][(d,t)]}")

    st.write(f"ค่าใช้จ่ายรวม: {result['total_cost']} บาท/สัปดาห์")



