# -*- coding: utf-8 -*-
"""app_ver.2

Automatically generated by Colab

Original file is located at
    https://colab.research.google.com/drive/121fXPIYPnaG28exA5pFoZh3ZgMM79fz2
"""
# Default employee availability
all_employees_avail = {
    1: {1:[1,2,3,4], 2:[], 3:[1,2,3,4], 4:[], 5:[], 6:[]},
    2: {1:[1,2,3,4], 2:[1,2,3,4], 3:[], 4:[], 5:[1,2,3,4], 6:[1,2,3,4]},
    # ... ใส่พนักงาน 3-16 ตามตัวอย่างของคุณ ...
}

# Default data dictionary
data = {
    "num_employees": 16,
    "W_per_t": {1:1, 2:2, 3:3, 4:2},
    "max_shift_i": 3,
    "P_idt": all_employees_avail,
    "cost_per_shift": {1:320, 2:160, 3:160, 4:160},
    "absent": {}  # ป้องกัน KeyError
}

# Default employee names
employee_names = ["Emp"+str(i) for i in range(1,17)]
num_employees = len(employee_names)

# app.py
import streamlit as st
from app_M2T1P8 import solver_parttime
import random, numpy as np

# --- ตั้ง seed ---
random.seed(42)
np.random.seed(42)

st.set_page_config(page_title="Part-time Scheduler", layout="wide")

st.title("🗓️ Part-time Employee Scheduler")
st.markdown("จัดตารางพนักงานพาร์ทไทม์สำหรับร้านอาหาร")

# --- กรอกชื่อพนักงาน ---
employee_names_input = st.text_input("กรอกชื่อพนักงาน (คั่นด้วย ,)")
employee_names = [name.strip() for name in employee_names_input.split(",") if name.strip()]
num_employees = len(employee_names)

# --- เลือกเดือน ---
month = st.selectbox("เลือกเดือน", ["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน",
                                     "กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"])

# --- กรอกเงื่อนไขพนักงาน ---
st.subheader("เงื่อนไขพนักงาน (วันและกะที่สะดวก)")
all_employees_avail = {}
day_map = {"อาทิตย์":1,"จันทร์":2,"อังคาร":3,"พุธ":4,"พฤหัส":5,"ศุกร์":6}
shift_map = {"1":1,"2":2,"3":3,"4":4}

for idx, name in enumerate(employee_names, start=1):
    with st.expander(f"{name}"):
        days = st.multiselect("วันสะดวก", list(day_map.keys()), key=f"days_{idx}")
        shifts = st.multiselect("กะสะดวก", list(shift_map.keys()), key=f"shifts_{idx}")
        emp_avail = {day_map[d]: [shift_map[s] for s in shifts] for d in days}
        all_employees_avail[idx] = emp_avail

# --- จำนวนพนักงานหลักต่อกะ ---
st.subheader("จำนวนพนักงานหลักต่อกะ")
W_per_t = {t: st.number_input(f"กะ {t}", min_value=0, value=1, step=1, key=f"main_{t}") for t in range(1,5)}

# --- จำนวนพนักงานสำรองต่อกะ ---
st.subheader("จำนวนพนักงานสำรองต่อกะ")
W_backup = {t: st.number_input(f"กะ {t}", min_value=0, value=1, step=1, key=f"backup_{t}") for t in range(1,5)}

# --- จำกัดจำนวนกะสูงสุด ---
max_shift = st.number_input("จำนวนกะสูงสุด/สัปดาห์ ต่อคน", min_value=1, value=3)

# --- ปุ่ม Solve ---
if st.button("สร้างตารางงาน"):
    data = {
        "num_employees": num_employees,
        "W_per_t": W_per_t,
        "max_shift_i": max_shift,
        "P_idt": all_employees_avail,
        "cost_per_shift": {1:320,2:160,3:160,4:160}
    }
    result = solver_parttime(data)

    st.success(f"ค่าใช้จ่ายรวม: {result['total_cost']} บาท/สัปดาห์")

    st.subheader("ตารางพนักงานหลัก (Main)")
    for d in range(1,7):
        st.write(f"Day {d}")
        for t in range(1,5):
            st.write(f"Shift {t}: {result['main'][(d,t)]}")

    st.subheader("ตารางพนักงานสำรอง (Backup)")
    for d in range(1,7):
        st.write(f"Day {d}")
        for t in range(1,5):
            st.write(f"Shift {t}: {result['backup'][(d,t)]}")

